const API_BASE = window.location.protocol === "file:"
    ? "http://localhost:3000"
    : window.location.origin;
const STORAGE_KEYS = {
    patient: "nexgen_patient",
    profile: "nexgen_profile",
    doctor: "nexgen_doctor",
    employee: "nexgen_employee",
    appointments: "nexgen_appointments",
    bills: "nexgen_bills"
};

function getStoredValue(key) {
    const raw = localStorage.getItem(key);
    return raw ? JSON.parse(raw) : null;
}

function setStoredValue(key, value) {
    localStorage.setItem(key, JSON.stringify(value));
}

function getStoredList(key) {
    return getStoredValue(key) || [];
}

function showMessage(element, message, type = "") {
    if (!element) {
        return;
    }

    element.textContent = message;
    element.className = `status-message ${type}`.trim();
}

function getLoggedInPatient() {
    return getStoredValue(STORAGE_KEYS.patient);
}

function getPatientProfile() {
    return getStoredValue(STORAGE_KEYS.profile);
}

function setLoggedInPatient(patient) {
    setStoredValue(STORAGE_KEYS.patient, patient);
}

function setPatientProfile(patient) {
    setStoredValue(STORAGE_KEYS.profile, patient);
}

async function tryPost(endpoint, payload) {
    const response = await fetch(`${API_BASE}${endpoint}`, {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(payload)
    });

    const contentType = response.headers.get("content-type") || "";
    const data = contentType.includes("application/json") ? await response.json() : await response.text();
    return { ok: response.ok, data };
}

async function tryPut(endpoint, payload) {
    const response = await fetch(`${API_BASE}${endpoint}`, {
        method: "PUT",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(payload)
    });

    const contentType = response.headers.get("content-type") || "";
    const data = contentType.includes("application/json") ? await response.json() : await response.text();
    return { ok: response.ok, data };
}

function ensureLoggedIn(redirectTarget = "dashboard.html") {
    if (!getLoggedInPatient()) {
        window.location.href = `login.html?redirect=${encodeURIComponent(redirectTarget)}`;
        return false;
    }
    return true;
}

function createDefaultBill(appointment) {
    return {
        billId: Date.now(),
        appointmentId: appointment.id,
        phone: appointment.phone,
        department: appointment.department,
        amount: 0,
        treatment: appointment.visitMode,
        status: "Generated by billing desk",
        paymentMode: "Offline only"
    };
}

function normalizeText(value) {
    return String(value || "").trim().toLowerCase();
}

function getDoctorDepartment(doctor) {
    return doctor.department || doctor.specialization || doctor.speciality || doctor.dept || "";
}

function getEmployeeRole(employee) {
    return employee.role || employee.designation || employee.employee_role || "";
}

function formatDateForInput(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");
    return `${year}-${month}-${day}`;
}

function formatTimeForInput(date) {
    const hours = String(date.getHours()).padStart(2, "0");
    const minutes = String(date.getMinutes()).padStart(2, "0");
    return `${hours}:${minutes}`;
}

function getNextAvailableAppointmentDate(now = new Date()) {
    const nextDate = new Date(now);
    if (now.getHours() >= 18) {
        nextDate.setDate(nextDate.getDate() + 1);
    }
    return formatDateForInput(nextDate);
}

function updateAppointmentDateTimeLimits() {
    const dateInput = document.getElementById("appointmentDate");
    const timeInput = document.getElementById("appointmentTime");
    if (!dateInput || !timeInput) {
        return;
    }

    const now = new Date();
    const today = formatDateForInput(now);
    const minBookableDate = getNextAvailableAppointmentDate(now);
    const selectedDate = dateInput.value || minBookableDate;

    dateInput.min = minBookableDate;
    if (!dateInput.value || dateInput.value < minBookableDate) {
        dateInput.value = minBookableDate;
    }

    timeInput.min = "09:00";
    timeInput.max = "18:00";

    if (selectedDate === today) {
        const currentTime = formatTimeForInput(now);
        timeInput.min = currentTime > "09:00" ? currentTime : "09:00";
    }

    if (timeInput.value) {
        if (timeInput.value < timeInput.min || timeInput.value > timeInput.max) {
            timeInput.value = "";
        }
    }
}

function isValidAppointmentSlot(dateValue, timeValue) {
    if (!dateValue || !timeValue) {
        return false;
    }

    const now = new Date();
    const today = formatDateForInput(now);
    const minBookableDate = getNextAvailableAppointmentDate(now);

    if (dateValue < minBookableDate) {
        return false;
    }

    if (timeValue < "09:00" || timeValue > "18:00") {
        return false;
    }

    if (dateValue === today) {
        const currentTime = formatTimeForInput(now);
        if (timeValue < (currentTime > "09:00" ? currentTime : "09:00")) {
            return false;
        }
    }

    return true;
}

function isBillingRole(role) {
    const normalized = normalizeText(role);
    return normalized.includes("billing");
}

function isCashierRole(role) {
    const normalized = normalizeText(role);
    return normalized.includes("cashier") || normalized.includes("payment");
}

function initProtectedLinks() {
    document.querySelectorAll("[data-protected-link]").forEach((button) => {
        button.addEventListener("click", () => {
            const target = button.getAttribute("data-protected-link");
            window.location.href = getLoggedInPatient()
                ? target
                : `login.html?redirect=${encodeURIComponent(target)}`;
        });
    });
}

function initLoginPage() {
    const patientForm = document.getElementById("patientLoginForm");
    if (!patientForm) {
        return;
    }

    const doctorForm = document.getElementById("doctorLoginForm");
    const employeeForm = document.getElementById("employeeLoginForm");
    const messageEl = document.getElementById("authMessage");
    const redirectTarget = new URLSearchParams(window.location.search).get("redirect") || "dashboard.html";

    document.querySelectorAll("[data-role-tab]").forEach((tab) => {
        tab.addEventListener("click", () => {
            const selectedRole = tab.getAttribute("data-role-tab");
            document.querySelectorAll("[data-role-tab]").forEach((item) => item.classList.toggle("is-active", item === tab));
            patientForm.classList.toggle("hidden", selectedRole !== "patient");
            doctorForm.classList.toggle("hidden", selectedRole !== "doctor");
            employeeForm.classList.toggle("hidden", selectedRole !== "employee");
            showMessage(messageEl, "");
        });
    });

    patientForm.addEventListener("submit", async (event) => {
        event.preventDefault();
        const formData = new FormData(patientForm);
        const phone = formData.get("phone").trim();
        const password = formData.get("password").trim();
        const savedProfile = getPatientProfile();

        if (!phone || !password) {
            showMessage(messageEl, "Enter your registered phone number and password.", "error");
            return;
        }

        try {
            const result = await tryPost("/login", { phone, password });
            if (result.ok && typeof result.data === "string" && /successful/i.test(result.data)) {
                const patient = savedProfile && savedProfile.phone === phone
                    ? savedProfile
                    : { name: "Patient", phone, age: "--", gender: "--", email: "" };
                setLoggedInPatient(patient);
                showMessage(messageEl, "Login successful. Redirecting...", "success");
                window.setTimeout(() => {
                    window.location.href = redirectTarget;
                }, 900);
                return;
            }
        } catch (error) {
            // Fall back to local registration data for preview mode.
        }

        if (savedProfile && savedProfile.phone === phone && savedProfile.password === password) {
            setLoggedInPatient(savedProfile);
            showMessage(messageEl, "Login successful. Redirecting...", "success");
            window.setTimeout(() => {
                window.location.href = redirectTarget;
            }, 900);
        } else {
            showMessage(messageEl, "Patient not registered. Please register first before logging in.", "error");
        }
    });

    doctorForm.addEventListener("submit", async (event) => {
        event.preventDefault();
        const formData = new FormData(doctorForm);
        const doctorId = formData.get("doctorId").trim();
        const password = formData.get("password").trim();

        if (!doctorId || !password) {
            showMessage(messageEl, "Enter doctor ID and password.", "error");
            return;
        }

        try {
            const result = await tryPost("/doctor-login", { doctorId, password });
            if (result.ok) {
                const doctorData = typeof result.data === "object" && result.data.doctor
                    ? result.data.doctor
                    : { doctor_id: doctorId, name: "Doctor" };
                setStoredValue(STORAGE_KEYS.doctor, doctorData);
                showMessage(messageEl, "Doctor login successful. Redirecting...", "success");
                window.setTimeout(() => {
                    window.location.href = "doctor-dashboard.html";
                }, 900);
                return;
            }
        } catch (error) {
            showMessage(messageEl, "Doctor login failed. Check doctor ID, password, or doctors table data.", "error");
            return;
        }

        showMessage(messageEl, "Doctor login was not accepted by the backend.", "error");
    });

    employeeForm.addEventListener("submit", async (event) => {
        event.preventDefault();
        const formData = new FormData(employeeForm);
        const employeeId = formData.get("employeeId").trim();
        const password = formData.get("password").trim();

        if (!employeeId || !password) {
            showMessage(messageEl, "Enter employee ID and password.", "error");
            return;
        }

        try {
            const result = await tryPost("/employee-login", { employeeId, password });
            if (result.ok) {
                const employeeData = typeof result.data === "object" && result.data.employee
                    ? result.data.employee
                    : { employee_id: employeeId, name: "Employee" };
                setStoredValue(STORAGE_KEYS.employee, employeeData);
                showMessage(messageEl, "Employee login successful. Redirecting...", "success");
                window.setTimeout(() => {
                    window.location.href = "employee-dashboard.html";
                }, 900);
                return;
            }
        } catch (error) {
            showMessage(messageEl, "Employee login failed. Check employee credentials or employee table data.", "error");
            return;
        }

        showMessage(messageEl, "Employee login was not accepted by the backend.", "error");
    });
}

function initRegisterPage() {
    const registerForm = document.getElementById("registerForm");
    if (!registerForm) {
        return;
    }

    const messageEl = document.getElementById("registerMessage");

    registerForm.addEventListener("submit", async (event) => {
        event.preventDefault();
        const formData = new FormData(registerForm);
        const patient = {
            name: formData.get("name").trim(),
            age: formData.get("age").trim(),
            gender: formData.get("gender").trim(),
            phone: formData.get("phone").trim(),
            email: formData.get("email").trim(),
            password: formData.get("password").trim()
        };

        if (!patient.name || !patient.age || !patient.gender || !patient.phone || !patient.password) {
            showMessage(messageEl, "Please fill in all required patient details.", "error");
            return;
        }

        try {
            await tryPost("/register", {
                name: patient.name,
                age: patient.age,
                gender: patient.gender,
                phone: patient.phone,
                password: patient.password
            });
        } catch (error) {
            // Keep local registration available for preview mode.
        }

        setPatientProfile(patient);
        setLoggedInPatient(null);
        localStorage.removeItem(STORAGE_KEYS.patient);
        showMessage(messageEl, "Registration completed. You can now log in as a patient.", "success");
        registerForm.reset();
        window.setTimeout(() => {
            window.location.href = "login.html";
        }, 1200);
    });
}

function renderAppointments() {
    const container = document.getElementById("appointmentsList");
    const patient = getLoggedInPatient();
    if (!container || !patient) {
        return;
    }

    const appointments = getStoredList(STORAGE_KEYS.appointments).filter((item) => item.phone === patient.phone);
    if (!appointments.length) {
        container.innerHTML = '<div class="record-item"><h4>No appointments yet</h4><p>Your booked consultations will appear here after submission.</p></div>';
        return;
    }

    container.innerHTML = appointments.map((appointment) => `
        <article class="record-item">
            <h4>${appointment.department}</h4>
            <p>${appointment.visitMode}</p>
            <p>${appointment.appointmentDate} at ${appointment.appointmentTime}</p>
            <p>Status: ${appointment.status}</p>
        </article>
    `).join("");
}

function renderBills() {
    const container = document.getElementById("billingList");
    const patient = getLoggedInPatient();
    if (!container || !patient) {
        return;
    }

    const bills = getStoredList(STORAGE_KEYS.bills).filter((item) => item.phone === patient.phone);
    if (!bills.length) {
        container.innerHTML = '<div class="billing-card"><h3>No bills generated yet</h3><p>The bill appears here only after the billing desk creates it after treatment or consultation.</p></div>';
        return;
    }

    container.innerHTML = bills.map((bill) => `
        <article class="billing-card">
            <h3>${bill.department}</h3>
            <p>Amount: Rs. ${bill.amount}</p>
            <p>Status: ${bill.status}</p>
            <p>Payment Mode: ${bill.paymentMode}</p>
            <p>Treatment: ${bill.treatment || "Consultation"}</p>
        </article>
    `).join("");
}

function updateLocalAppointmentStatus(appointmentId, status) {
    const appointments = getStoredList(STORAGE_KEYS.appointments).map((appointment) =>
        String(appointment.id) === String(appointmentId)
            ? { ...appointment, status }
            : appointment
    );
    setStoredValue(STORAGE_KEYS.appointments, appointments);
}

function updateLocalBillStatus(billId, status) {
    const bills = getStoredList(STORAGE_KEYS.bills).map((bill) =>
        String(bill.billId) === String(billId)
            ? { ...bill, status }
            : bill
    );
    setStoredValue(STORAGE_KEYS.bills, bills);
}

function renderDoctorAppointments() {
    const container = document.getElementById("doctorAppointmentsList");
    if (!container) {
        return;
    }

    const doctor = getStoredValue(STORAGE_KEYS.doctor);
    const doctorDepartment = normalizeText(getDoctorDepartment(doctor));
    const appointments = getStoredList(STORAGE_KEYS.appointments).filter((appointment) =>
        normalizeText(appointment.department) === doctorDepartment
    );
    if (!appointments.length) {
        container.innerHTML = '<div class="record-item"><h4>No department appointments yet</h4><p>Only appointments matching your department are shown here.</p></div>';
        return;
    }

    container.innerHTML = appointments.map((appointment) => `
        <article class="record-item">
            <div class="panel-header">
                <div>
                    <h4>${appointment.department}</h4>
                    <p>Patient Phone: ${appointment.phone}</p>
                </div>
                <span class="status-badge">${appointment.status}</span>
            </div>
            <p>Visit Type: ${appointment.visitMode}</p>
            <p>Date: ${appointment.appointmentDate}</p>
            <p>Time: ${appointment.appointmentTime}</p>
            <p>Problem: ${appointment.problem}</p>
            ${appointment.status === "Pending" ? `
                <div class="record-item-actions">
                    <button class="mini-button accept" type="button" data-appointment-action="Accepted" data-appointment-id="${appointment.id}">Accept</button>
                    <button class="mini-button reject" type="button" data-appointment-action="Rejected" data-appointment-id="${appointment.id}">Reject</button>
                </div>
            ` : ""}
        </article>
    `).join("");
}

function renderProfile() {
    const patient = getLoggedInPatient();
    const welcomeHeading = document.getElementById("welcomeHeading");
    const overviewProblem = document.getElementById("overviewProblem");
    const profileCard = document.getElementById("profileCard");

    if (!patient || !profileCard) {
        return;
    }

    welcomeHeading.textContent = `Welcome, ${patient.name}`;
    overviewProblem.textContent = `Registered profile: ${patient.age} years old, ${patient.gender || "gender not provided"}.`;
    profileCard.innerHTML = `
        <div class="profile-row"><span>Patient Name</span><span>${patient.name}</span></div>
        <div class="profile-row"><span>Age</span><span>${patient.age}</span></div>
        <div class="profile-row"><span>Gender</span><span>${patient.gender || "Not provided"}</span></div>
        <div class="profile-row"><span>Phone</span><span>${patient.phone}</span></div>
        <div class="profile-row"><span>Email</span><span>${patient.email || "Not provided"}</span></div>
    `;
}

function initDashboardPage() {
    const appointmentForm = document.getElementById("appointmentForm");
    if (!appointmentForm) {
        return;
    }

    if (!ensureLoggedIn("dashboard.html")) {
        return;
    }

    renderProfile();
    renderAppointments();
    renderBills();

    const appointmentMessage = document.getElementById("appointmentMessage");
    const patient = getLoggedInPatient();
    const appointmentDateInput = document.getElementById("appointmentDate");

    updateAppointmentDateTimeLimits();
    appointmentDateInput.addEventListener("change", updateAppointmentDateTimeLimits);

    appointmentForm.addEventListener("submit", async (event) => {
        event.preventDefault();
        updateAppointmentDateTimeLimits();
        const formData = new FormData(appointmentForm);
        const appointment = {
            id: Date.now(),
            phone: patient.phone,
            department: formData.get("department").trim(),
            appointmentDate: formData.get("appointmentDate"),
            appointmentTime: formData.get("appointmentTime"),
            visitMode: formData.get("visitMode"),
            problem: formData.get("problem").trim(),
            status: "Pending"
        };

        if (!isValidAppointmentSlot(appointment.appointmentDate, appointment.appointmentTime)) {
            showMessage(appointmentMessage, "Appointments can only be booked from today onward, during hospital hours from 9:00 AM to 6:00 PM.", "error");
            return;
        }

        try {
            await tryPost("/book", {
                patient_id: 1,
                doctor_id: 1,
                problem: appointment.problem,
                appointment_date: appointment.appointmentDate,
                appointment_time: appointment.appointmentTime
            });
        } catch (error) {
            // Preview flow stays available without backend connectivity.
        }

        const appointments = getStoredList(STORAGE_KEYS.appointments);
        appointments.unshift(appointment);
        setStoredValue(STORAGE_KEYS.appointments, appointments);

        appointmentForm.reset();
        showMessage(appointmentMessage, "Appointment request sent successfully.", "success");
        renderAppointments();
        renderBills();
    });

    document.getElementById("logoutButton").addEventListener("click", () => {
        localStorage.removeItem(STORAGE_KEYS.patient);
        window.location.href = "index.html";
    });
}

function initDoctorDashboardPage() {
    const doctorHeading = document.getElementById("doctorWelcomeHeading");
    if (!doctorHeading) {
        return;
    }

    const doctor = getStoredValue(STORAGE_KEYS.doctor);
    if (!doctor) {
        window.location.href = "login.html";
        return;
    }

    const doctorName = doctor.name || doctor.doctor_name || "Doctor";
    const doctorId = doctor.doctor_id || doctor.id || "-";
    const doctorDepartment = getDoctorDepartment(doctor) || "Not assigned";

    doctorHeading.textContent = `Welcome, ${doctorName}`;
    document.getElementById("doctorNameValue").textContent = doctorName;
    document.getElementById("doctorIdValue").textContent = doctorId;
    document.getElementById("doctorDepartmentValue").textContent = doctorDepartment;
    renderDoctorAppointments();

    const messageEl = document.getElementById("doctorAppointmentMessage");
    const appointmentList = document.getElementById("doctorAppointmentsList");

    appointmentList.addEventListener("click", async (event) => {
        const button = event.target.closest("[data-appointment-action]");
        if (!button) {
            return;
        }

        const appointmentId = button.getAttribute("data-appointment-id");
        const status = button.getAttribute("data-appointment-action");

        try {
            await tryPut(`/update-status/${appointmentId}`, { status });
        } catch (error) {
            // Keep doctor workflow active for local preview data.
        }

        updateLocalAppointmentStatus(appointmentId, status);
        renderDoctorAppointments();
        showMessage(messageEl, `Appointment ${status.toLowerCase()} successfully.`, "success");
    });

    document.getElementById("doctorLogoutButton").addEventListener("click", () => {
        localStorage.removeItem(STORAGE_KEYS.doctor);
        window.location.href = "index.html";
    });
}

function renderBillingDeskAppointments() {
    const container = document.getElementById("billingAppointmentsList");
    if (!container) {
        return;
    }

    const bills = getStoredList(STORAGE_KEYS.bills);
    const billedAppointmentIds = new Set(bills.map((bill) => String(bill.appointmentId)));
    const appointments = getStoredList(STORAGE_KEYS.appointments).filter((appointment) =>
        appointment.status === "Accepted" && !billedAppointmentIds.has(String(appointment.id))
    );

    if (!appointments.length) {
        container.innerHTML = '<div class="record-item"><h4>No appointments ready for billing</h4><p>Accepted appointments without a bill will appear here for billing desk processing.</p></div>';
        return;
    }

    container.innerHTML = appointments.map((appointment) => `
        <article class="record-item">
            <h4>${appointment.department}</h4>
            <p>Patient Phone: ${appointment.phone}</p>
            <p>Date: ${appointment.appointmentDate}</p>
            <p>Visit Type: ${appointment.visitMode}</p>
            <p>Problem: ${appointment.problem}</p>
            <div class="record-item-actions">
                <input class="bill-amount-input" type="number" min="0" placeholder="Enter bill amount" data-bill-input="${appointment.id}">
                <button class="mini-button accept" type="button" data-generate-bill="${appointment.id}">Generate Bill</button>
            </div>
        </article>
    `).join("");
}

function renderEmployeeBills() {
    const container = document.getElementById("employeeBillsList");
    if (!container) {
        return;
    }

    const bills = getStoredList(STORAGE_KEYS.bills).filter((bill) => bill.status === "Generated by billing desk");
    if (!bills.length) {
        container.innerHTML = '<div class="record-item"><h4>No cashier payments pending</h4><p>Billing desk must generate a bill first. Only then will it appear here for cashier payment acceptance.</p></div>';
        return;
    }

    container.innerHTML = bills.map((bill) => `
        <article class="record-item">
            <div class="panel-header">
                <div>
                    <h4>${bill.department}</h4>
                    <p>Patient Phone: ${bill.phone}</p>
                </div>
                <span class="status-badge">${bill.status}</span>
            </div>
            <p>Bill Amount: Rs. ${bill.amount}</p>
            <p>Payment Mode: ${bill.paymentMode}</p>
            <p>Treatment: ${bill.treatment || "Consultation"}</p>
            ${bill.status === "Generated by billing desk" ? `
                <div class="record-item-actions">
                    <button class="mini-button accept" type="button" data-bill-action="Paid" data-bill-id="${bill.billId}">Accept Payment</button>
                </div>
            ` : ""}
        </article>
    `).join("");
}

function initEmployeeDashboardPage() {
    const employeeHeading = document.getElementById("employeeWelcomeHeading");
    if (!employeeHeading) {
        return;
    }

    const employee = getStoredValue(STORAGE_KEYS.employee);
    if (!employee) {
        window.location.href = "login.html";
        return;
    }

    const employeeName = employee.name || employee.employee_name || "Employee";
    const employeeId = employee.employee_id || employee.id || "-";
    const employeeRole = getEmployeeRole(employee) || "billing / cashier";
    const billingSection = document.getElementById("billing-desk");
    const cashierSection = document.getElementById("cashier-desk");

    employeeHeading.textContent = `Welcome, ${employeeName}`;
    document.getElementById("employeeNameValue").textContent = employeeName;
    document.getElementById("employeeIdValue").textContent = employeeId;
    document.getElementById("employeeRoleValue").textContent = employeeRole;

    if (isBillingRole(employeeRole) && !isCashierRole(employeeRole)) {
        cashierSection.classList.add("hidden");
    } else if (isCashierRole(employeeRole) && !isBillingRole(employeeRole)) {
        billingSection.classList.add("hidden");
    }

    renderBillingDeskAppointments();
    renderEmployeeBills();

    const billingMessageEl = document.getElementById("billingDeskMessage");
    const cashierMessageEl = document.getElementById("cashierDeskMessage");
    const billingAppointmentsList = document.getElementById("billingAppointmentsList");
    const billList = document.getElementById("employeeBillsList");

    billingAppointmentsList.addEventListener("click", async (event) => {
        const button = event.target.closest("[data-generate-bill]");
        if (!button) {
            return;
        }

        const appointmentId = button.getAttribute("data-generate-bill");
        const amountInput = document.querySelector(`[data-bill-input="${appointmentId}"]`);
        const amount = Number(amountInput ? amountInput.value : 0);
        if (!amount || amount <= 0) {
            showMessage(billingMessageEl, "Enter a valid bill amount before generating the bill.", "error");
            return;
        }

        const appointment = getStoredList(STORAGE_KEYS.appointments).find((item) => String(item.id) === String(appointmentId));
        if (!appointment) {
            showMessage(billingMessageEl, "Appointment not found for bill generation.", "error");
            return;
        }

        try {
            await tryPost("/generate-bill", {
                appointment_id: appointmentId,
                amount
            });
        } catch (error) {
            // Keep local billing desk workflow available.
        }

        const bills = getStoredList(STORAGE_KEYS.bills);
        const bill = createDefaultBill(appointment);
        bill.amount = amount;
        bills.unshift(bill);
        setStoredValue(STORAGE_KEYS.bills, bills);

        renderBillingDeskAppointments();
        renderEmployeeBills();
        showMessage(billingMessageEl, "Bill generated successfully and now visible to the patient and cashier.", "success");
    });

    billList.addEventListener("click", async (event) => {
        const button = event.target.closest("[data-bill-action]");
        if (!button) {
            return;
        }

        const billId = button.getAttribute("data-bill-id");
        const status = button.getAttribute("data-bill-action");

        try {
            await tryPut(`/payment/${billId}`, { status });
        } catch (error) {
            // Keep payment desk preview flow working without backend connectivity.
        }

        updateLocalBillStatus(billId, status);
        renderEmployeeBills();
        showMessage(cashierMessageEl, `Billing status updated to ${status}.`, "success");
    });

    document.getElementById("employeeLogoutButton").addEventListener("click", () => {
        localStorage.removeItem(STORAGE_KEYS.employee);
        window.location.href = "index.html";
    });
}

document.addEventListener("DOMContentLoaded", () => {
    initProtectedLinks();
    initLoginPage();
    initRegisterPage();
    initDashboardPage();
    initDoctorDashboardPage();
    initEmployeeDashboardPage();
});
